### Actuator Health
GET http://localhost:8080/api/actuator/health

### Auth Health
GET http://localhost:8080/api/auth/health

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

### Consultar usuário autenticado
GET http://localhost:8080/api/auth/me
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIwNjU2NjZlMS05YzlmLTQyMmEtYmNjYS0yZjRkNjE2NmZjNjUiLCJpYXQiOjE3NTc4OTE4MjUsImV4cCI6MTc1Nzg5MjQyNSwianRpIjoiNTk2YjEwNjItMDc1Yy00YzViLWE1ODgtNWQwYjMwYzRjZTZiIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGVzIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwicGVybWlzc2lvbnMiOlsic3lzdGVtOnJlYWQiLCJzeXN0ZW06YWRtaW4iLCJ1c2VyOm1hbmFnZSIsInN5c3RlbTp3cml0ZSJdLCJlbmFibGVkIjp0cnVlfQ.xNb4v0ARUL17oC6XO5mgLEXn-sIE2mo2YcDbxqQZAWVabAz48yzVOaHpnhGnrsAietSp9H4SilzcYEIFipLPj4nVIBAhvrqJ6jO3z31YsvFGv7A-_5WjvOOXvg-kHs8aBCtIMDXzIdJ4XP0cZxTTX8vjm--VJCW9yETgpdSQcELeIoXrqeOifRK1kaUmtp7GocZck3TTXACHufJVwMwkt_azeBgEik7gtSnnWXrez4x89kEHzmbZC8PSXXiyAiKYkGI2v1hlafQlMqXna5FY32aqF-Drsd89JcvHV2wOgyRRWtEtK94MJmzBLWSAjwx_FauxHgmUvhOIvKtGtsd5B4v1qqypVo-UCgasYO4FDSWJzyk2caLKCWtcS3vefGb8gjG5qpwA0Nsj_25j8ASaM5wtHdQqOfe4EJIO2OnlMxjQKsh9gkJOUERnMHk-NBclXbKFGsu_cAhLuZq6D6jsFrbMF1mX4yl1IdhTznpYJbzTONhUJXg5gZh6vBmLkAnC

### Refresh de token
POST http://localhost:8080/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "f443b319-baca-4f76-b119-06565ee5f8a1"
}

### Logout
POST http://localhost:8080/api/auth/logout
Content-Type: application/json

{
  "refreshToken": "f443b319-baca-4f76-b119-06565ee5f8a1"
}
